import { Service, Benefit, BlogPost, Testimonial, FAQItem } from './types';

export const SERVICES: Service[] = [
  {
    id: 'mapa-numerologico-integral',
    title: 'Mapa Numerológico Integral',
    category: 'autoconhecimento',
    description: 'Decodificação profunda do seu nome e data de nascimento para revelar sua missão de vida, talentos e destino.',
    fullDescription: 'O Mapa Numerológico Integral é um guia profundo de autoconhecimento. Através da análise matemática e simbólica de seu nome e data de nascimento, identificamos seus números de alma, personalidade, destino e missão de vida. Uma bússola indispensável para compreender seus ciclos e alinhar suas escolhas ao seu propósito original.',
    iconName: 'Hash',
    duration: 'Análise personalizada + Relatório de 40+ páginas',
  },
  {
    id: 'guia-astrologico-anual',
    title: 'Guia Astrológico Anual',
    category: 'autoconhecimento',
    description: 'Previsões astrológicas e orientações para os seus próximos 12 meses com base nos trânsitos e revolução solar.',
    fullDescription: 'O Guia Astrológico Anual analisa as principais tendências e trânsitos astrológicos sobre o seu mapa de nascimento nos próximos 12 meses. Compreenda os períodos de maior propensão ao crescimento profissional, afetivo e pessoal, permitindo que você tome decisões conscientes e aproveite o fluxo cósmico a seu favor.\n\nDescubra:\n- Tendências de janeiro a dezembro\n- Momentos de expansão\n- Meses de cautela\n- Os meses mais potentes para decisões\n- Tendências emocionais do ano\n- O que precisa ser curado ou transformado\n- As oportunidades que não pode perder\n- Mudanças importantes em todos aspectos da vida\n- Os trânsitos astrológicos mais te afetarão\n- As oportunidades mais fortes do ano\n- Movimentos internos (progressões)',
    iconName: 'CalendarRange',
    duration: 'Análise Personalizada + Relatório completo e detalhado sobre cada aspecto do seu Guia Astrológico',
  },
  {
    id: 'mapa-astral-pessoal',
    title: 'Mapa Astral Pessoal',
    category: 'autoconhecimento',
    description: 'Fotografia do céu no momento exato do seu nascimento, revelando a estrutura profunda da sua personalidade.',
    fullDescription: 'Uma análise profunda do posicionamento dos planetas, signos e casas astrológicas na hora exata do seu nascimento. O Mapa Astral Pessoal é uma ferramenta definitiva de autoconhecimento que revela seus padrões psicológicos, forças inatas, desafios emocionais e o caminho ideal para sua realização.',
    iconName: 'Compass',
    duration: 'Relatório personalizado e detalhado sobre cada aspecto do seu Mapa Astral Pessoal em formato PDF com mais de 40 páginas',
  },
  {
    id: 'mapa-astral-empresarial',
    title: 'Mapa Astral Empresarial',
    category: 'autoconhecimento',
    description: 'Direcionamento estratégico e energético para negócios, analisando o momento de fundação e ciclos da empresa.',
    fullDescription: 'O Mapa Astral Empresarial é voltado para empreendedores e líderes que buscam alinhar suas marcas ao fluxo da prosperidade. Analisamos a data de registro ou fundação da empresa para identificar a identidade do negócio, forças de mercado, desafios de gestão e os melhores momentos para lançamentos, contratações e expansões.',
    iconName: 'Briefcase',
    duration: 'Análise estratégica + relatório detalhado em formato PDF',
  },
  {
    id: 'sinastria-de-relacionamentos',
    title: 'Sinastria de Relacionamentos',
    category: 'autoconhecimento',
    description: 'Estudo de compatibilidade e dinâmicas energéticas entre duas pessoas para harmonização de laços.',
    fullDescription: 'A Sinastria de Relacionamentos é o estudo da compatibilidade entre duas pessoas através da comparação detalhada dos seus Mapas Astrais. Esta análise revela os pontos de harmonia que fortalecem a conexão e os pontos de tensão que pedem atenção e crescimento mútuo — seja em relacionamentos amorosos, familiares, de amizade ou profissionais.\n\nAtravés da sobreposição dos mapas, identificamos como as energias de cada pessoa interagem: onde há fluidez e apoio mútuo, onde há atrito e aprendizado, e como ambos podem crescer juntos respeitando suas individualidades. Não se trata de determinar se um relacionamento "dá certo", mas de compreender sua dinâmica para vivê-lo com mais consciência, respeito e amor.\n\nA análise considera os planetas pessoais de ambos (Sol, Lua, Mercúrio, Vênus, Marte), os aspectos entre eles, as casas ativadas e os padrões que emergem da interação entre os dois mapas.\n\nIdeal para casais, sócios ou familiares, este estudo revela pontos de profunda afinidade, aprendizados mútuos, desafios de comunicação e caminhos práticos para construir uma relação equilibrada, respeitosa e harmoniosa.',
    iconName: 'HeartHandshake',
    duration: 'Relatório detalhado completo em PDF',
  },
  {
    id: 'blindagem-energetica-integral',
    title: 'Blindagem Energética Integral',
    category: 'harmonizacao',
    description: 'Processo robusto de proteção e fortalecimento do campo vibracional contra energias nocivas externas.',
    fullDescription: 'A Blindagem Energética Integral utiliza técnicas de Radiestesia e frequências da Radiônica para estruturar uma barreira protetora ao redor do seu campo áurico. Ideal para pessoas altamente sensíveis (esponjas energéticas) , que lidam com ambientes densos e de alta exposição social, que sentem cansaço constante, peso emocional, irritação sem motivo, energia drenada ou sensação de estar absorvendo problemas dos outros, A Blindagem oferece limpeza, harmonização , selamento  do  campo  energético,  garantindo integridade e estabilidade emocional.',
    iconName: 'ShieldCheck',
    duration: 'Tratamento radiônico à distância de 21 dias',
  },
  {
    id: 'limpeza-energetica-integral',
    title: 'Limpeza Energética Integral',
    category: 'harmonizacao',
    description: 'Desobstrução completa de miasmas, formas-pensamento e bloqueios estagnados nos corpos sutis.',
    fullDescription: 'Você sente cansaço constante, peso emocional, ambientes carregados, irritação sem motivo, energia drenada ou sensação de estar absorvendo problemas dos outros? Seu campo energético pode precisar de limpeza, reorganização e proteção. Este atendimento realiza uma varredura completa em seu campo bioenergético, removendo bloqueios, energias intrusas, cordões energéticos adoecidos e formas-pensamento estagnadas. Uma verdadeira desintoxicação vibracional que devolve o vigor, a leveza física e a clareza mental necessárias para o seu dia a dia.',
    iconName: 'Sparkles',
    duration: 'Tratamento de desobstrução e alinhamento',
  },
  {
    id: 'limpeza-energetica-de-ambientes',
    title: 'Limpeza Energética de Ambientes',
    category: 'ambientes-e-pets',
    description: 'Harmonização de residências e empresas para dissolver bloqueios, melhorar o sono e atrair prosperidade.',
    fullDescription: 'Casas e escritórios absorvem e retêm a energia das pessoas que os frequentam e dos eventos que neles ocorrem. Realizamos um diagnóstico radiestésico minucioso das energias telúricas (do solo), memórias de parede e correntes eletromagnéticas neles presentes. Em seguida, aplicamos gráficos radiônicos para transmutar e elevar o padrão vibratório do local, promovendo paz, saúde, sono reparador e prosperidade.',
    iconName: 'Home',
    duration: 'Análise energética completa do ambiente + tratamento radiônico e relatório (devolutiva)',
  },
  {
    id: 'harmonizacao-de-chakras',
    title: 'Harmonização de Chakras',
    category: 'harmonizacao',
    description: 'Alinhamento e calibração dos sete centros de energia principais para reestabelecer o bem-estar e a vitalidade.',
    fullDescription: 'Os Chakras são os centros responsáveis pela distribuição de energia vital pelo nosso organismo. Utilizando pêndulos específicos e frequências fitoenergéticas, medimos e regulamos cada um dos sete chakras principais, dissolvendo bloqueios que se manifestam como cansaço físico, ansiedade ou apatia emocional.',
    iconName: 'Activity',
    duration: 'Análise energética completa dos chakras + tratamento radiônico de harmonização e relatório completo (devolutiva)',
  },
  {
    id: 'harmonizacao-da-aura',
    title: 'Harmonização da Aura',
    category: 'harmonizacao',
    description: 'Restauração de fendas e fortalecimento do campo luminoso que envolve e protege o corpo físico.',
    fullDescription: 'A Aura é o nosso escudo de luz. Fendas e desgastes no campo áurico podem causar fadiga inexplicável, irritabilidade e vulnerabilidade energética. Com ferramentas radiônicas de alta precisão, reestruturamos as camadas áuricas, selando fissuras e restabelecendo sua luminosidade e integridade protetora natural.',
    iconName: 'Sun',
    duration: 'Análise energética completa + tratamento radiônico de harmonização e relatório completo (devolutiva)',
  },
  {
    id: 'harmonizacao-dos-corpos-sutis',
    title: 'Harmonização dos Corpos Sutis',
    category: 'harmonizacao',
    description: 'Sincronização entre os corpos mental, emocional, etérico e espiritual para alinhamento existencial.',
    fullDescription: 'Nós não somos apenas um corpo físico, mas sim um sistema integrado de corpos sutis (emocional, mental, espiritual). Quando há um descompasso entre eles, sentimos incoerência interna. Este tratamento atua especificamente nas camadas sutis para alinhar suas intenções racionais com seus sentimentos e ações diárias.',
    iconName: 'Layers',
    duration: 'Análise energética completa + tratamento radiônico integrado + relatório completo (devolutiva)',
  },
  {
    id: 'harmonizacao-pet',
    title: 'Harmonização Pet',
    category: 'ambientes-e-pets',
    description: 'Tratamento sutil de Radiestesia e Fitoenergética para animais de estimação, auxiliando em estresse e saúde.',
    fullDescription: 'Nossos queridos cães, gatos e outros animais são esponjas extremamente sensíveis ao ambiente e às emoções dos tutores. A Harmonização Pet atua de forma gentil e não invasiva, utilizando gráficos radiônicos e fitoenergética adaptada para reduzir quadros de ansiedade de separação, agressividade, dores crônicas ou acelerar a recuperação pós-cirúrgica.',
    iconName: 'Heart',
    duration: 'Tratamento à distância focado no bem-estar animal',
  },
  {
    id: 'divorcio-energetico',
    title: 'Divórcio Energético',
    category: 'harmonizacao',
    description: 'Desconexão saudável de cordões energéticos e dependências emocionais de relacionamentos passados.',
    fullDescription: 'Nem todo vínculo termina quando a convivência acaba.\nMuitas conexões permanecem ativas no campo energético, influenciando emoções, pensamentos, decisões e até bloqueando prosperidade, relacionamentos e paz interior.\n\nEsses laços podem surgir de relações amorosas, vínculos familiares difíceis, amizades desgastadas, sociedades rompidas, promessas feitas no passado, pactos inconscientes, contratos energéticos repetitivos e até padrões herdados de ancestrais.\n\nQuando essas conexões deixam de nutrir e passam a pesar, é o momento de realizar um Divórcio Energético.\n\nO que é Divórcio Energético?\nÉ um processo terapêutico realizado através da Radiestesia e Radiônica, com o objetivo de identificar, harmonizar e encerrar vínculos energéticos nocivos que continuam atuando em sua vida.\n\nNão significa apagar pessoas, negar histórias ou destruir memórias importantes. Pelo contrário:\nTudo o que foi aprendizado, amor, crescimento, proteção e boas trocas é preservado.\n\nO que se trabalha para dissolver são apenas cargas negativas, dores, dependências, manipulações, promessas limitantes, culpas, ressentimentos, amarras e energias que já não servem ao seu bem maior.\n\nÉ uma forma consciente de fechar ciclos com respeito e leveza.\n\nQuais vínculos podem ser trabalhados?\n\n* Relacionamentos amorosos encerrados\n* Ex-parceiros que ainda geram apego ou sofrimento\n* Laços familiares tóxicos ou desgastantes\n* Amizades rompidas que ainda pesam emocionalmente\n* Sociedades profissionais mal resolvidas\n* Pactos e promessas inconscientes\n* Contratos energéticos repetitivos\n* Padrões ancestrais de dor, escassez ou abandono\n* Situações do passado que ainda drenam sua energia\n* Apego excessivo e doloroso a entes que já partiram\n\nBenefícios do Divórcio Energético:\n\n* Sensação de leveza e alívio emocional\n* Liberação de padrões repetitivos\n* Clareza mental para seguir em frente\n* Redução de apego e dependência emocional\n* Fortalecimento da autoestima\n* Mais energia vital e disposição\n* Abertura de caminhos no amor e prosperidade\n* Harmonização interior\n* Paz ao lembrar do passado, sem sofrimento\n* Reconexão com sua própria força.',
    iconName: 'Scissors',
    duration: 'Tratamento radiônico avançado para limpeza, corte de laços e liberação de energias aprisionantes + relatório PDF(devolutiva)',
  },
  {
    id: 'mesa-radionica-para-prosperidade',
    title: 'Mesa Radiônica para Prosperidade',
    category: 'prosperidade',
    description: 'Ativação de frequências financeiras e abertura de caminhos profissionais através de geometria sagrada.',
    fullDescription: 'A Mesa Radiônica é uma ferramenta que atua no nível subatômico e quântico. Com foco na área financeira e profissional, identificamos as frequências de estagnação, crenças limitantes herdadas ou externas e, através do pêndulo e da geometria sagrada, ativamos portais de abertura de caminhos, sorte, conexões benéficas e oportunidades abundantes.',
    iconName: 'Flame',
    duration: 'Ativação quântica + Relatório de envio',
  },
  {
    id: 'mapa-da-prosperidade',
    title: 'Mapa da Prosperidade',
    category: 'prosperidade',
    description: 'Estudo personalizado das energias de abundância presentes no seu Mapa Natal e Numerológico.',
    fullDescription: 'Sente que sua vida financeira poderia fluir mais, mas algo parece travar?\n\nMuitas vezes não é falta de esforço.\nExistem bloqueios inconscientes, padrões de escassez e ciclos energéticos que podem limitar prosperidade, oportunidades e crescimento.\n\nO Mapa da Prosperidade é um diagnóstico minucioso que une Astrologia e Numerologia sob a ótica da prosperidade material e espiritual. Descubra qual é a sua área vocacional mais lucrativa, seus maiores bloqueios com o dinheiro, crenças limitantes, o número de poder pessoal que atrai prosperidade e como sintonizar a mente subconsciente na abundância.\n\nO Mapa te mostra o que está bloqueando sua prosperidade, como você pode se conectar com o fluxo de abundância e manifestar uma vida de liberdade financeira.\n\nUm diagnóstico profundo que inclui:\n\n✔ Identificação de bloqueios ocultos que limitam sua abundância\n✔ Análise dos arquétipos de escassez que podem estar atuando na sua vida\n✔ Análise astrológica do seu mapa astral, destacando os pontos ligados a dinheiro, prosperidade e expansão\n✔ Análise numerológica baseada no seu nome, revelando aspectos vibracionais relacionados a prosperidade e fluxo financeiro\n✔ Direcionamento para ativar seu fluxo de prosperidade pessoal ou profissional',
    iconName: 'TrendingUp',
    duration: 'Análise profunda em PDF+ Indicação de práticas personalizadas que te levarão  a alcançar o fluxo da prosperidade abundante.',
  },
  {
    id: 'desbloqueio-financeiro-energetico',
    title: 'Desbloqueio Financeiro Energético',
    category: 'prosperidade',
    description: 'Remoção de crenças limitantes e auto-sabotagem instaladas no inconsciente financeiro do indivíduo.',
    fullDescription: 'Muitas vezes, a escassez financeira não se deve à falta de esforço, mas a votos inconscientes de pobreza, medos herdados ou sentimentos de não-merecimento instalados no campo energético familiar. Este tratamento desprograma essas frequências estagnadas e instala uma nova assinatura vibracional de fluxo livre de abundância em sua vida.\n\nO que trabalha:\n* Limpeza de padrões de escassez\n* Crenças limitantes sobre dinheiro\n* Medo de prosperar\n* Auto sabotagem financeira\n* Bloqueios ancestrais ligados à pobreza\n* Dificuldade de receber dinheiro\n* Energia parada profissionalmente\n* Falta de clientes e oportunidades\n* Desorganização vibracional material\n* Materialização de metas e objetivos\n\nBenefícios percebidos:\n* Mais clareza financeira\n* Sensação de caminhos abrindo\n* Motivação para agir\n* Melhor relação com dinheiro\n* Mais oportunidades\n* Campo vibracional mais forte\n* Redução de medo e travas\n* Foco em metas\n* Energia de crescimento',
    iconName: 'DollarSign',
    duration: 'Tratamento continuado de 14 dias',
  }
];

export const BENEFITS: Benefit[] = [
  {
    id: 'equilibrio',
    title: 'Mais Equilíbrio',
    description: 'Sinta a estabilidade emocional e mental retornar ao seu dia a dia, neutralizando as oscilações bruscas de humor e o cansaço inexplicável.',
    iconName: 'Scale',
  },
  {
    id: 'clareza',
    title: 'Mais Clareza',
    description: 'Dissolva a névoa mental e tome decisões importantes com total assertividade, sabedoria e alinhamento com a sua verdade interior.',
    iconName: 'Eye',
  },
  {
    id: 'protecao',
    title: 'Proteção Energética',
    description: 'Aprenda a blindar o seu campo vibratório contra interferências externas, protegendo sua paz e mantendo sua vitalidade blindada.',
    iconName: 'Shield',
  },
  {
    id: 'prosperidade',
    title: 'Prosperidade Alinhada',
    description: 'Remova os entraves ocultos que impedem o fluxo de dinheiro, atraindo novos negócios, parcerias sólidas e conquistas materiais.',
    iconName: 'Coins',
  },
  {
    id: 'bem-estar',
    title: 'Bem-Estar Integral',
    description: 'Restabeleça a harmonia física, reduzindo os efeitos do estresse crônico, melhorando a vitalidade celular e resgatando seu ânimo diário.',
    iconName: 'Heart',
  },
  {
    id: 'autoconhecimento',
    title: 'Autoconhecimento Profundo',
    description: 'Descubra sua assinatura energética única, compreendendo sua personalidade, dons natos e as lições evolutivas da sua jornada terrena.',
    iconName: 'Sparkles',
  },
  {
    id: 'harmonia-familiar',
    title: 'Harmonia Familiar',
    description: 'Transmute tensões e conflitos nos relacionamentos íntimos, promovendo uma atmosfera de acolhimento, diálogo amoroso e compreensão mútua.',
    iconName: 'Users',
  },
  {
    id: 'ambientes-leves',
    title: 'Ambientes Mais Leves',
    description: 'Purifique sua casa ou local de trabalho, transformando espaços anteriormente tensos em verdadeiros santuários de descanso e criatividade.',
    iconName: 'Home',
  },
  {
    id: 'qualidade-vida',
    title: 'Qualidade de Vida',
    description: 'Viva em congruência espiritual e prática, desfrutando de noites de sono restauradoras, paz mental e uma profunda alegria de viver.',
    iconName: 'Smile',
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Helena Vasconcellos',
    role: 'Arquiteta e Urbanista',
    rating: 5,
    text: 'A Limpeza de Ambientes na minha residência mudou completamente a atmosfera. Meu filho pequeno que não conseguia dormir direto no quarto dele passou a dormir a noite toda. Sinto um acolhimento e uma paz indescritíveis ao entrar em casa hoje. O trabalho é extremamente sério e livre de misticismos exagerados.',
    serviceName: 'Limpeza Energética de Ambientes',
  },
  {
    id: '2',
    name: 'Roberto Mendonça',
    role: 'Diretor de Tecnologia',
    rating: 5,
    text: 'Como cético, confesso que me surpreendi com a Mesa Radiônica de Prosperidade. Duas semanas após a sessão de ativação, um contrato que estava travado há mais de 8 meses na burocracia governamental foi liberado e assinado. A clareza mental e o profissionalismo no atendimento me conquistaram completamente.',
    serviceName: 'Mesa Radiônica para Prosperidade',
  },
  {
    id: '3',
    name: 'Mariana Drummond',
    role: 'Psicóloga Clínica',
    rating: 5,
    text: 'A Sinastria de Relacionamento e o Mapa Astral Pessoal me deram um entendimento profundo sobre os meus padrões afetivos e como eu estava repetindo comportamentos de auto-sabotagem. Recomendo a todos os meus pacientes como uma terapia integrativa complementar ao processo analítico.',
    serviceName: 'Mapa Astral Pessoal',
  },
  {
    id: '4',
    name: 'Carla & Pedro Siqueira',
    role: 'Tutor de Golden Retriever (Tobias)',
    rating: 5,
    text: 'O Tobias estava sofrendo muito com ansiedade de separação severa, uivando o dia todo quando saíamos e desenvolvendo alergias de pele de origem emocional. O tratamento de Harmonização Pet trouxe uma serenidade inacreditável para ele. Ele está calmo, feliz e as feridinhas sumiram inteiramente. Sem palavras!',
    serviceName: 'Harmonização Pet',
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'ciencia-radiestesia',
    title: 'A Ciência Sutil por trás da Radiestesia e da Radiônica',
    category: 'Radiestesia',
    summary: 'Compreenda como as frequências vibratórias e as emissões de formas afetam diretamente nossa biologia e os ambientes.',
    content: 'A radiestesia é a sensibilidade à radiação e aos campos de energia que nos cercam. Longe de ser um conceito puramente esotérico, a radiestesia é amparada pela física contemporânea, que compreende que tudo o que existe no universo vibra em frequências específicas. Nosso sistema nervoso atua como uma antena receptora extremamente sofisticada, capaz de detectar pequenas variações nesses campos magnéticos e telúricos. Através de instrumentos como o pêndulo, essa resposta neuromuscular sutil é amplificada e traduzida. A radiônica, por sua vez, é a ciência que atua na emissão e harmonização dessas frequências através de padrões geométricos matematicamente calculados, reestabelecendo a ordem em campos bioenergéticos desregulados.',
    date: '15 Jun, 2026',
    readTime: '6 min de leitura',
    imageUrl: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'fitoenergetica-ambiente',
    title: 'Fitoenergética: O Poder Oculto das Plantas no Equilíbrio Diário',
    category: 'Fitoenergética',
    summary: 'Como a assinatura energética das ervas pode nos auxiliar a limpar pensamentos obsessivos e atrair serenidade.',
    content: 'Enquanto a fitoterapia utiliza os princípios químicos ativos das plantas para a cura física, a fitoenergética atua no campo vibracional dos vegetais. Cada planta carrega uma frequência espiritual e emocional única. Ervas como o Alecrim elevam a vibração mental e estimulam o foco, enquanto a Guiné atua purificando o duplo etérico de miasmas e inveja. Aprender a combinar o chá fitoenergético correto com gráficos radiônicos específicos potencializa de forma extraordinária o reequilíbrio da aura e dos chakras.',
    date: '08 Jun, 2026',
    readTime: '5 min de leitura',
    imageUrl: 'https://images.unsplash.com/photo-1545241047-6083a3684587?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'fluxo-prosperidade-bloqueios',
    title: 'Desbloqueio Financeiro: Rompendo Votos de Escassez no Inconsciente',
    category: 'Prosperidade',
    summary: 'Identifique os três sinais de que o seu fluxo financeiro está sofrendo interferências energéticas hereditárias.',
    content: 'Muitas vezes nos deparamos com o chamado "teto invisível" financeiro: por mais que trabalhemos ou ganhemos dinheiro, ele escorre por entre os dedos ou surgem imprevistos que drenam as economias. Na Akashaterapia, investigamos se há "votos de pobreza" inconscientes herdados do sistema familiar ou pactos de escassez que operam em nível espiritual sutil. Ao limpar essas frequências utilizando a radiônica voltada à prosperidade, removemos esses pesos, permitindo que a energia do dinheiro – que é puramente neutra e expansiva – encontre livre trânsito em sua vida material.',
    date: '28 Mai, 2026',
    readTime: '7 min de leitura',
    imageUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?auto=format&fit=crop&q=80&w=600',
  },
  {
    id: 'animais-esponjas-energeticas',
    title: 'Por que os animais de estimação absorvem as cargas dos tutores?',
    category: 'Bem-estar',
    summary: 'Entenda a profunda sensibilidade dos pets e como protegê-los de sobrecargas emocionais no ambiente familiar.',
    content: 'Cães e gatos possuem um campo áurico extremamente dilatado e receptivo. Por puro amor incondicional e proximidade biológica, eles costumam atuar como "filtros biológicos" de suas casas. Quando os tutores passam por crises prolongadas de ansiedade, depressão ou discussões constantes, o animal absorve essa frequência para tentar aliviar o sofrimento da família. Com o tempo, essa sobrecarga pode se manifestar em comportamentos obsessivos, lambedura de patas, problemas renais ou de pele. A terapia de Harmonização Pet reestabelece a ordem energética do animal, devolvendo-lhe leveza e vitalidade.',
    date: '14 Mai, 2026',
    readTime: '5 min de leitura',
    imageUrl: 'https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&q=80&w=600',
  }
];

export const FAQS: FAQItem[] = [
  {
    id: 'faq-1',
    category: 'Geral',
    question: 'O que é a Akashaterapia e como ela funciona?',
    answer: 'A Akashaterapia é um método de harmonização energética integrada que une ferramentas científicas-sutis (Radiestesia e Radiônica) com saberes ancestrais estruturados (Astrologia, Numerologia, Fitoenergética). Ela atua identificando os bloqueios vibracionais presentes em pessoas, animais de estimação ou ambientes através de gráficos radiônicos de alta precisão e pêndulos específicos, efetuando o alinhamento das frequências para restabelecer o equilíbrio e abrir caminhos para a saúde, bem-estar e prosperidade.',
  },
  {
    id: 'faq-2',
    category: 'Sessões',
    question: 'As consultas e tratamentos podem ser feitos inteiramente à distância?',
    answer: 'Sim, absolutamente. No plano quântico-energético, não existem barreiras de tempo ou espaço físico. A Radiestesia e a Mesa Radiônica operam através do campo de ressonância morfogenética, utilizando o testemunho do interagente (nome completo, data de nascimento e assinatura energética) para realizar medições precisas e emitir frequências terapêuticas à distância. Os relatórios de diagnóstico e as sessões de mentoria são fornecidos em PDF detalhado e de fácil compreensão.',
  },
  {
    id: 'faq-3',
    category: 'Misticismo',
    question: 'A Akashaterapia está ligada a alguma religião ou crença mística?',
    answer: 'Não. Nosso posicionamento segue a estética e a prática do Luxo Holístico Contemporâneo. Nosso trabalho é baseado em biofísica sutil, geometria de formas e radiestesia técnica clássica. Não realizamos promessas milagrosas, trabalhos de amarração ou qualquer ritual esotérico de cunho supersticioso. Nosso foco é o desenvolvimento humano consciente, a reordenação de frequências desreguladas e a tomada de decisão assertiva e profissional.',
  },
  {
    id: 'faq-4',
    category: 'Pets',
    question: 'Como funciona o atendimento para animais de estimação?',
    answer: 'O atendimento Pet é realizado à distância e de forma totalmente indolor e não invasiva. O tutor fornece o nome do animal, foto, idade e relata as queixas principais (físicas ou comportamentais). Analisamos energeticamente os chakras do pet, medimos sua vitalidade e aplicamos frequências equilibradoras de fitoenergética e gráficos radiônicos voltados à proteção e cicatrização. É uma excelente terapia integrativa complementar ao tratamento médico veterinário convencional.',
  },
  {
    id: 'faq-5',
    category: 'Ambientes',
    question: 'Como sei se minha casa ou empresa precisa de uma limpeza energética?',
    answer: 'Os sinais mais comuns de sobrecarga vibracional em ambientes incluem: sensação de cansaço extremo ou irritabilidade inexplicável logo após entrar no local, insônia constante, aparelhos eletrônicos ou lâmpadas queimando com frequência incomum, plantas murchando rapidamente mesmo bem cuidadas, e conflitos ou discussões recorrentes sem motivos aparentes. A limpeza restaura a harmonia e o fluxo dinâmico de prosperidade do espaço.',
  },
  {
    id: 'faq-6',
    category: 'Resultados',
    question: 'Em quanto tempo é possível perceber os benefícios dos tratamentos?',
    answer: 'Os benefícios sutis, como melhora na qualidade do sono, leveza mental, diminuição da ansiedade e sensação de paz profunda, costumam ser relatados logo nos primeiros dias de ativação radiônica. Para questões mais densas, como desbloqueios financeiros ou reordenação de dinâmicas familiares complexas, os efeitos consolidados aparecem gradativamente ao longo do período do tratamento (geralmente entre 14 e 21 dias) e das mudanças comportamentais conscientes recomendadas.',
  }
];
